### ISSUE TITLE
Can i ues it in windows

### ISSUE THREAD

**Issue by zhangbozhi01** [evanwashere/duckdb#7]
I am interested in using duckdb on Windows with Deno. Could you please inform if there are plans to support native bindings for Windows?
TS```
const path = {
  linux() {
    return new URL(`./bin/libduckdb.so`, import.meta.url);
  },
  darwin() {
    return new URL(`./bin/libduckdb.dylib`, import.meta.url);
  },
}[Deno.build.os]().pathname;
```
When the code execution reaches this point, an error is encountered.

**Comment by evanwashere** [comment]
This library currently only targets bun but I might consider Deno support in future
